/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InviteEntryRouteImport } from './routes/invite-entry'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as MarketplaceRouteRouteImport } from './routes/marketplace/_route'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardInvitesRouteImport } from './routes/dashboard/invites'
import { Route as ApiAuthValidateInviteRouteImport } from './routes/api/auth/validate-invite'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthCallbackGoogleRouteImport } from './routes/api/auth/callback/google'

const MarketplaceRouteImport = createFileRoute('/marketplace')()

const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteEntryRoute = InviteEntryRouteImport.update({
  id: '/invite-entry',
  path: '/invite-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const MarketplaceRouteRoute = MarketplaceRouteRouteImport.update({
  id: '/_route',
  getParentRoute: () => MarketplaceRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvitesRoute = DashboardInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthValidateInviteRoute = ApiAuthValidateInviteRouteImport.update({
  id: '/api/auth/validate-invite',
  path: '/api/auth/validate-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackGoogleRoute = ApiAuthCallbackGoogleRouteImport.update({
  id: '/api/auth/callback/google',
  path: '/api/auth/callback/google',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/invite-entry': typeof InviteEntryRoute
  '/login': typeof LoginRoute
  '/dashboard/invites': typeof DashboardInvitesRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/marketplace': typeof MarketplaceRouteRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/validate-invite': typeof ApiAuthValidateInviteRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite-entry': typeof InviteEntryRoute
  '/login': typeof LoginRoute
  '/dashboard/invites': typeof DashboardInvitesRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/validate-invite': typeof ApiAuthValidateInviteRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/invite-entry': typeof InviteEntryRoute
  '/login': typeof LoginRoute
  '/dashboard/invites': typeof DashboardInvitesRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/marketplace/_route': typeof MarketplaceRouteRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/validate-invite': typeof ApiAuthValidateInviteRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/invite-entry'
    | '/login'
    | '/dashboard/invites'
    | '/dashboard/users'
    | '/marketplace'
    | '/dashboard/'
    | '/marketplace/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/validate-invite'
    | '/api/auth/callback/google'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite-entry'
    | '/login'
    | '/dashboard/invites'
    | '/dashboard/users'
    | '/marketplace'
    | '/dashboard'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/validate-invite'
    | '/api/auth/callback/google'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/invite-entry'
    | '/login'
    | '/dashboard/invites'
    | '/dashboard/users'
    | '/marketplace'
    | '/marketplace/_route'
    | '/dashboard/'
    | '/marketplace/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/validate-invite'
    | '/api/auth/callback/google'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  InviteEntryRoute: typeof InviteEntryRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthValidateInviteRoute: typeof ApiAuthValidateInviteRoute
  ApiAuthCallbackGoogleRoute: typeof ApiAuthCallbackGoogleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite-entry': {
      id: '/invite-entry'
      path: '/invite-entry'
      fullPath: '/invite-entry'
      preLoaderRoute: typeof InviteEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/marketplace/_route': {
      id: '/marketplace/_route'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invites': {
      id: '/dashboard/invites'
      path: '/invites'
      fullPath: '/dashboard/invites'
      preLoaderRoute: typeof DashboardInvitesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/validate-invite': {
      id: '/api/auth/validate-invite'
      path: '/api/auth/validate-invite'
      fullPath: '/api/auth/validate-invite'
      preLoaderRoute: typeof ApiAuthValidateInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback/google': {
      id: '/api/auth/callback/google'
      path: '/api/auth/callback/google'
      fullPath: '/api/auth/callback/google'
      preLoaderRoute: typeof ApiAuthCallbackGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardInvitesRoute: typeof DashboardInvitesRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardInvitesRoute: DashboardInvitesRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface MarketplaceRouteChildren {
  MarketplaceRouteRoute: typeof MarketplaceRouteRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceRouteRoute: MarketplaceRouteRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  InviteEntryRoute: InviteEntryRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthValidateInviteRoute: ApiAuthValidateInviteRoute,
  ApiAuthCallbackGoogleRoute: ApiAuthCallbackGoogleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
